engines:
  eslint:
    enabled: true
    exclude_fingerprints:
    - 481dd35fe9d0159a29146031423d935d
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
