language: node_js
node_js:
- 5.10.1
sudo: false
notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
addons:
  code_climate:
    repo_token: eea1f32d56a3c36788ad2a85540fae519760ddc8f179fedf60693977085d08bb
before_deploy:
  - export PKG_RELEASE=$(ls ./NGN.js lib/*.js lib/exception/*.js lib/rpc/*.js package.json LICENSE)
  - echo "deploying ${PKG_RELEASE} to GitHub releases"
deploy:
  - provider: npm
    email: sysadmin@coreybutler.com
    api_key:
      secure: MZxXBK0/84Lagwx8SbhVxXgwrPwRr/R8dBbzSNZHk+gki/w7r/TvgFIUJKOfEkBGpBhBIRHrJh3K9wudkJRqYLrSNWLq0Ea59vO7rZ0AIws11OZRuxgIPCyy5YBmF3Pr6SY3uIuyqPS3p2CaUO3t4oXVfMDSMA66qFVMt5b79d4=
    on:
      tags: true
      repo: ngnjs/NGN
  - provider: releases
    api_key:
      secure: ZcWoKlPJI3vhYxNchE5gdpZBfwRo9khsfwbHK1Mz//dO+lnWDKY5UjVutOSQM86VDM3BGiy7kkWC7Em08GRKuTbLIFGBWTEJi2DdnR97rmYaGbBOjmgZdmI4gQL+yB3pusPOfOn6rY8kocpfxPlTQSAj724Ypo3qemZTCHSEKH4=
    file: "${PKG_RELEASE}"
    skip_cleanup: true
    on:
      tags: true
      repo: ngnjs/NGN
after_success:
  - curl -g -H "Content-Type:\ application/json" -d '{"ngn":"'$TRAVIS_TAG'","trigger":"ngnjs\/docker-ngn-base"}' -X POST "${POSTOP_URL}"
