language: node_js
node_js:
- 4.2.1
sudo: false
notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
addons:
  code_climate:
    repo_token: eea1f32d56a3c36788ad2a85540fae519760ddc8f179fedf60693977085d08bb
before_deploy:
  - export RELEASE_PKG=$(ls ./NGN.js lib/*.js lib/exception/*.js lib/rpc/*.js package.json LICENSE)
  - echo "deploying $RELEASE_PKG to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: ZcWoKlPJI3vhYxNchE5gdpZBfwRo9khsfwbHK1Mz//dO+lnWDKY5UjVutOSQM86VDM3BGiy7kkWC7Em08GRKuTbLIFGBWTEJi2DdnR97rmYaGbBOjmgZdmI4gQL+yB3pusPOfOn6rY8kocpfxPlTQSAj724Ypo3qemZTCHSEKH4=
  skip_cleanup: true
  file_glob: true
  file: "${RELEASE_PKG}"
  on:
    repo: ngnjs/NGN
    tags: true
