language: node_js
node_js:
- 4.2.1
sudo: false
notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    format: html
addons:
  code_climate:
    repo_token: eea1f32d56a3c36788ad2a85540fae519760ddc8f179fedf60693977085d08bb
# before_deploy:
# - export RELEASE_PKG=$(ls ./NGN.js lib/*.js lib/exception/*.js lib/rpc/*.js package.json
#   LICENSE)
# - echo "deploying $RELEASE_PKG to GitHub releases"
deploy:
  provider: npm
  email: corey@coreybutler.com
  api_key:
    secure: DbvI7ialsnF7TwncBZUO6gu++yQjnqqE37ZR3R6v7hHwoYL3S53HhsWCNmweFrj/BZkriAyaHYfra73mDePwceQdHq0nO1eUvSOCtl1UqmENe3ClWHiMHQmqB2wwJi0DCd5es2lU5wWYe4Jr0b5elr4cjBduaDlSAip2JXqOvaI=
  on:
    tags: true
    repo: ngnjs/NGN
